"""Subtitler builder — turn transcript_polished.json into word-by-word cues.

Pure determinista:
  1. Flatten every word from every segment, preserving order.
  2. Clean text, drop empty/timing-less words (with a note).
  3. Trim each word's `end_s` so it never overlaps the next word's `start_s`
     (word disappears the instant the next one starts — spec §4.2).
  4. Enforce a minimum visible duration (`MIN_DUR_S`); if the next word starts
     sooner than that, accept the shorter window — never push timestamps.
"""
from __future__ import annotations

import logging
from datetime import datetime, timezone
from typing import Iterable

from .contracts import SubtitleClip, SubtitleClips, SubtitleStyle

log = logging.getLogger("subtitler.builder")

MIN_DUR_S = 0.08          # 80ms floor — below this the word would flicker
MAX_GAP_FILL_S = 0.05     # if a gap to next word ≤ 50ms, extend current word to fill


def _iter_words(transcript: dict) -> Iterable[tuple[int, dict]]:
    """Yield (segment_index, word_dict) in narrative order."""
    for seg_idx, seg in enumerate(transcript.get("segments") or []):
        for w in seg.get("words") or []:
            yield seg_idx, w


def _clean_text(raw: str | None) -> str:
    if not raw:
        return ""
    # Whisper sometimes prefixes a leading space; strip and collapse internals.
    return " ".join(raw.split()).strip()


def build_clips(
    transcript: dict,
    *,
    style: SubtitleStyle | None = None,
) -> SubtitleClips:
    """Build the SubtitleClips structure from a polished transcript dict."""
    sb = SubtitleClips(
        created_at=datetime.now(timezone.utc),
        language=transcript.get("language") or "en",
        duration_s=float(transcript.get("duration_s") or 0.0),
        style=style or SubtitleStyle(),
    )

    raw: list[tuple[int, float, float, str]] = []
    for seg_idx, w in _iter_words(transcript):
        text = _clean_text(w.get("text"))
        s = w.get("start_s")
        e = w.get("end_s")
        if not text:
            continue
        if s is None or e is None:
            sb.notes.append(f"seg{seg_idx}: word '{text}' missing timestamps; skipped")
            continue
        s_f, e_f = float(s), float(e)
        if e_f < s_f:
            sb.notes.append(f"seg{seg_idx}: word '{text}' end<start ({s_f:.3f}>{e_f:.3f}); skipped")
            continue
        raw.append((seg_idx, s_f, e_f, text))

    # Trim ends so we never overlap, optionally fill micro-gaps.
    for i, (seg_idx, s, e, text) in enumerate(raw):
        if i + 1 < len(raw):
            next_start = raw[i + 1][1]
            if e > next_start:
                e = next_start
            elif (next_start - e) <= MAX_GAP_FILL_S:
                e = next_start
        # Floor to min duration if there's room.
        if (e - s) < MIN_DUR_S:
            if i + 1 < len(raw):
                e = min(s + MIN_DUR_S, raw[i + 1][1])
            else:
                e = max(s + MIN_DUR_S, e)
        sb.clips.append(SubtitleClip(
            index=len(sb.clips) + 1,
            start_s=round(s, 3),
            end_s=round(e, 3),
            text=text,
            segment_index=seg_idx,
        ))

    return sb


def _fmt_srt_time(t: float) -> str:
    if t < 0:
        t = 0.0
    h = int(t // 3600)
    m = int((t % 3600) // 60)
    s = int(t % 60)
    ms = int(round((t - int(t)) * 1000))
    if ms == 1000:
        s, ms = s + 1, 0
    return f"{h:02d}:{m:02d}:{s:02d},{ms:03d}"


def _fmt_ass_time(t: float) -> str:
    if t < 0:
        t = 0.0
    h = int(t // 3600)
    m = int((t % 3600) // 60)
    s = t % 60
    cs = int(round((s - int(s)) * 100))
    s_int = int(s)
    if cs == 100:
        s_int, cs = s_int + 1, 0
    return f"{h:d}:{m:02d}:{s_int:02d}.{cs:02d}"


def render_srt(clips: SubtitleClips) -> str:
    """Standard SRT: one cue per word."""
    out: list[str] = []
    for c in clips.clips:
        out.append(str(c.index))
        out.append(f"{_fmt_srt_time(c.start_s)} --> {_fmt_srt_time(c.end_s)}")
        out.append(c.text)
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def render_ass(clips: SubtitleClips) -> str:
    """ASS for CapCut/Remotion. Pill is approximated with a thick black border;
    the compositor will render the proper rounded pill using `subtitle_clips.json`.
    """
    st = clips.style
    play_w, play_h = 1080, 1920
    margin_v = int(round((1.0 - st.y_anchor_norm) * play_h))
    bold = -1 if st.bold else 0

    header = (
        "[Script Info]\n"
        "; Generated by myavatar v6 subtitler\n"
        "ScriptType: v4.00+\n"
        f"PlayResX: {play_w}\n"
        f"PlayResY: {play_h}\n"
        "ScaledBorderAndShadow: yes\n"
        "WrapStyle: 2\n"
        "\n"
        "[V4+ Styles]\n"
        "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, "
        "OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, "
        "ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, "
        "Alignment, MarginL, MarginR, MarginV, Encoding\n"
        f"Style: Pill,{st.font},{st.font_size},{st.primary_color},"
        f"{st.primary_color},{st.pill_color},{st.pill_color},"
        f"{bold},0,0,0,100,100,0,0,3,8,0,2,40,40,{margin_v},1\n"
        "\n"
        "[Events]\n"
        "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, "
        "Effect, Text\n"
    )

    fade_tag = f"{{\\fad({st.fade_in_ms},{st.fade_out_ms})}}"
    lines: list[str] = []
    for c in clips.clips:
        text = c.text.replace("\n", " ").replace(",", "،")  # ASS uses comma as field sep
        lines.append(
            f"Dialogue: 0,{_fmt_ass_time(c.start_s)},{_fmt_ass_time(c.end_s)},"
            f"Pill,,0,0,0,,{fade_tag}{text}"
        )

    return header + "\n".join(lines) + "\n"
